"""create coffee factor chain tables

Revision ID: 0fb3d1d90b4f
Revises: 
Create Date: 2026-09-12 21:19:57.028598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fb3d1d90b4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brew_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coffee_id', sa.String(), nullable=False),
    sa.Column('recommended_methods', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('water_temperature_celsius', sa.Float(), nullable=True),
    sa.Column('grind_size', sa.String(), nullable=True),
    sa.Column('ratio', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coffee_id')
    )
    op.create_table('causal_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coffee_id', sa.String(), nullable=False),
    sa.Column('from_factor', sa.String(), nullable=False),
    sa.Column('to_factor', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coffee_id', sa.String(), nullable=False),
    sa.Column('altitude_meters', sa.Integer(), nullable=False),
    sa.Column('shade_type', sa.String(), nullable=False),
    sa.Column('avg_temperature_celsius', sa.Float(), nullable=True),
    sa.Column('annual_rainfall_mm', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coffee_id')
    )
    op.create_table('flavor_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coffee_id', sa.String(), nullable=False),
    sa.Column('tasting_notes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('acidity', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('sweetness', sa.String(), nullable=False),
    sa.Column('aftertaste', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coffee_id')
    )
    op.create_table('origins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coffee_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('municipality', sa.String(), nullable=False),
    sa.Column('farm_name', sa.String(), nullable=False),
    sa.Column('producer', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coffee_id')
    )
    op.create_table('processing_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coffee_id', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('fermentation_hours', sa.Float(), nullable=True),
    sa.Column('drying_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coffee_id')
    )
    op.create_table('roast_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coffee_id', sa.String(), nullable=False),
    sa.Column('roast_level', sa.String(), nullable=False),
    sa.Column('development_time_percent', sa.Float(), nullable=True),
    sa.Column('roaster_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coffee_id')
    )
    op.create_table('varieties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coffee_id', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('cultivar', sa.String(), nullable=False),
    sa.Column('rootstock', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coffee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('varieties')
    op.drop_table('roast_profiles')
    op.drop_table('processing_methods')
    op.drop_table('origins')
    op.drop_table('flavor_profiles')
    op.drop_table('environments')
    op.drop_table('causal_links')
    op.drop_table('brew_methods')
    op.drop_table('coffees')
    # ### end Alembic commands ###
